[package]
name = "rdclicker_reborn"
version = "0.6.1"
edition = "2021"

[dependencies]
windows = {version="~0.58",features=["Win32_UI_Input_KeyboardAndMouse"]}
toml="~0.8"
serde = { version = "1.0", features = ["derive"] }

[profile.release]
opt-level = 2
